export default {
  students: ['Student One', 'Student Two'],
  teachers: ['Dan Seethaler', 'New Teacher'],
  dates: [
    {
      id: 'recPI7zsJa3ia73nY',
      date: '2018-08-27',
      type: 'class',
      lessonCount: 2,
    },
    {
      id: 'reckTEMPuyVi6bKKr',
      date: '2018-08-28',
      type: 'flex',
      lessonCount: 1,
      substitute: 'Jeremy',
    },
    {
      id: 'recz19EuQQutViqg6',
      date: '2018-08-29',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recSRBZozyIqaQzTL',
      date: '2018-08-30',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rechT4tYmY5Husx1T',
      date: '2018-08-31',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'reczvNdTic6oEgv3Y',
      date: '2018-09-03',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Labor Day',
      teacher_swap: true,
    },
    {
      id: 'recXCDOTTlpHlRfnx',
      date: '2018-09-04',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recCKPrDWOJz6NfER',
      date: '2018-09-05',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec9DuGxZz5JSWWrr',
      date: '2018-09-06',
      type: 'cancelled',
      lessonCount: 1,
      notes: 'Snow day!',
    },
    {
      id: 'recaKcDdihAcJYWfK',
      date: '2018-09-07',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec8CI8HjSNIGQnsw',
      date: '2018-09-10',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recI8HnTFBIpriiSZ',
      date: '2018-09-11',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recKlY1APZaHM0guy',
      date: '2018-09-12',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recXTmIFI8qopGSqw',
      date: '2018-09-13',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recW9KLdiXpeJrd0b',
      date: '2018-09-14',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recqS2lryn9XRv2cN',
      date: '2018-09-17',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec4RHW3cO26ExMCS',
      date: '2018-09-18',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recChR0OYsohi8Ka4',
      date: '2018-09-19',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'reccbHgSDmXxGqSWm',
      date: '2018-09-20',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recdCKzl1do89qWfO',
      date: '2018-09-21',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'recBxs1TSObZtPOCj',
      date: '2018-09-24',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'receAh2EwechtzaOX',
      date: '2018-09-25',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recoDF0gLxzRHxsHB',
      date: '2018-09-26',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recxXbxuouzGAkz0l',
      date: '2018-09-27',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recbLXTEVekAwCK6r',
      date: '2018-09-28',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recSVFxMsyVLKDXDF',
      date: '2018-10-01',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recglvGI748PEIK04',
      date: '2018-10-02',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recZTb7fyiQm2iQ4w',
      date: '2018-10-03',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec4CgN0KOzDXhVlJ',
      date: '2018-10-04',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec40ZEy8u6GidxIJ',
      date: '2018-10-05',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recBcOdCpRqoybZgc',
      date: '2018-10-08',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recVT1PXnpApedukC',
      date: '2018-10-09',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recvyMFgqr0Ke3Ibt',
      date: '2018-10-10',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recXmLruvKBcwjFPG',
      date: '2018-10-11',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recdyZTbmJ0R30Bqf',
      date: '2018-10-12',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'recPc6FF7nBikbpFG',
      date: '2018-10-15',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recVrbV6ysBWNswrZ',
      date: '2018-10-16',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recf3H9hry3fBQByY',
      date: '2018-10-17',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recu6jegDlLyV6QjQ',
      date: '2018-10-18',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recxFkO6sXJPz4APn',
      date: '2018-10-19',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recfgxiRSdMJO0Azi',
      date: '2018-10-22',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'reci9G8ggQQbe3gIQ',
      date: '2018-10-23',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recSAGdlAuU2BeE0t',
      date: '2018-10-24',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recaI67BwPtdHVuRf',
      date: '2018-10-25',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recW80reQStY0deY0',
      date: '2018-10-26',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recDPY7uX9frfz0RM',
      date: '2018-10-29',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Teacher Work Day',
    },
    {
      id: 'recPfYZDrUHZqZcms',
      date: '2018-10-30',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Teacher Work Day',
    },
    {
      id: 'receuBTFtDO3yzBQq',
      date: '2018-10-31',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rectE7vb2PztqeqxE',
      date: '2018-11-01',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rectKzj7cGFGMKHKK',
      date: '2018-11-02',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recCi2sjJWW2vm5is',
      date: '2018-11-05',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recBWHkkXTbwAoabk',
      date: '2018-11-06',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'reck8Oqzrfaoa8HP3',
      date: '2018-11-07',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recWN03BWkFesPC3Q',
      date: '2018-11-08',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec20zi8WQTgJjQKE',
      date: '2018-11-09',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'rec1xxgSrnZOQEGNe',
      date: '2018-11-12',
      type: 'holiday',
      lessonCount: 1,
      notes: "Veteran's Day",
    },
    {
      id: 'recBPWywDXtf3WHde',
      date: '2018-11-13',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recl5ny0BQO3kqYLq',
      date: '2018-11-14',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recqi4Por8TYX9vah',
      date: '2018-11-15',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recggZAWrVtKsAgWo',
      date: '2018-11-16',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recsCHcVXNGeft8mM',
      date: '2018-11-19',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recTCmUXIAnQrWRRb',
      date: '2018-11-20',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recogorSdTqfGs8Gn',
      date: '2018-11-21',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Thanksgiving',
    },
    {
      id: 'rec4ihqSVibFct8ZH',
      date: '2018-11-22',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Thanksgiving',
    },
    {
      id: 'recC9MC3SIXo3XTCJ',
      date: '2018-11-23',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Thanksgiving',
    },
    {
      id: 'recg1isPEvIJI8Zbi',
      date: '2018-11-26',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recCKf7sZWbHiDa04',
      date: '2018-11-27',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec8cKxW8HKwp915N',
      date: '2018-11-28',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recq5t65oWMo3tZaS',
      date: '2018-11-29',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recimvtwDvQ4sYl7u',
      date: '2018-11-30',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recCrGzFQGCB5PXbn',
      date: '2018-12-03',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec1C63tRMNUZjgK8',
      date: '2018-12-04',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recquyz85tAX674nv',
      date: '2018-12-05',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'reclZtV1AGZVBSVTB',
      date: '2018-12-06',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recMom8Q495hBOrU6',
      date: '2018-12-07',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'recx8DAPgcjnMVnCZ',
      date: '2018-12-10',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recbxDdYEAIrQcfI0',
      date: '2018-12-11',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recYBIWGw3qg59D6q',
      date: '2018-12-12',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recIcZm8uth2eBzUL',
      date: '2018-12-13',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recc39J7Nj1XpTjc4',
      date: '2018-12-14',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recIQTKncBddvFh4w',
      date: '2018-12-17',
      type: 'assessment',
      lessonCount: 1,
    },
    {
      id: 'recgg9Mtvo5nWF9tb',
      date: '2018-12-18',
      type: 'assessment',
      lessonCount: 1,
    },
    {
      id: 'recrMuhpa2uaTueWr',
      date: '2018-12-19',
      type: 'party',
      lessonCount: 1,
    },
    {
      id: 'recFMfSJDjDqL9ID2',
      date: '2018-12-20',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'recpfqZiQ7cyDv8To',
      date: '2018-12-21',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'recp3OpA1NCCW99Lt',
      date: '2018-12-24',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'recoXNtiZlxrNDCcS',
      date: '2018-12-25',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'recs2JFU3FoPBlSJs',
      date: '2018-12-26',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'recxOIHgzYyGbSuDP',
      date: '2018-12-27',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'recwXhTB5Tf08aoJG',
      date: '2018-12-28',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'recFZVqFUGK4MSrKR',
      date: '2018-12-31',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'recuE2TbozhDd1EVN',
      date: '2019-01-01',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Winter Break',
    },
    {
      id: 'rec23vSfegPnk81sy',
      date: '2019-01-02',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec9xviTNPW3eOAGW',
      date: '2019-01-03',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recb9mYmMghXjISC0',
      date: '2019-01-04',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recPWpdlDVwIttH3A',
      date: '2019-01-07',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recxGNRrU1tBJYWKn',
      date: '2019-01-08',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recO6OVxYD6scqeMh',
      date: '2019-01-09',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recYBIBRN3QWJaw9j',
      date: '2019-01-10',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'reco0BAaVlFDYG22q',
      date: '2019-01-11',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'rec9l86R66l4RvulF',
      date: '2019-01-14',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recqBknYEYnQ0Kyio',
      date: '2019-01-15',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'reciVztJKYSgmlYzh',
      date: '2019-01-16',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recpE3Qqi0LwcbwXF',
      date: '2019-01-17',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recjrF59lHLnhWJgo',
      date: '2019-01-18',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recSgmiTFEVL308vw',
      date: '2019-01-21',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Martin Luther King Jr.',
    },
    {
      id: 'recMqXy1uu7Y4KQ1S',
      date: '2019-01-22',
      type: 'holiday',
      lessonCount: 1,
      notes: ' Teacher Workday',
    },
    {
      id: 'recmi84TOR4JmLu4c',
      date: '2019-01-23',
      type: 'holiday',
      lessonCount: 1,
      notes: ' Teacher Workday',
    },
    {
      id: 'recwuGSAaewCJEmLD',
      date: '2019-01-24',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recwIaUlj9N4LAYWS',
      date: '2019-01-25',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recUQnRexM6cCxT3w',
      date: '2019-01-28',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recwQgeEBTxsADkOP',
      date: '2019-01-29',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recMuSquRU8g3cSLq',
      date: '2019-01-30',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recNkSnYjy6ryZ15k',
      date: '2019-01-31',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recwluwMjzJ6WFfRB',
      date: '2019-02-01',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recDlQkve3pj7igMf',
      date: '2019-02-04',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rece49z7Vxxwk3WcX',
      date: '2019-02-05',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec2Fz5I7HhSZgNhl',
      date: '2019-02-06',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'reciDrOzc0kb5lB6D',
      date: '2019-02-07',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec8YvCaDpzBfbZni',
      date: '2019-02-08',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'recIiOfqdGsxJBHpP',
      date: '2019-02-11',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec6YynGyTZ4UiyFd',
      date: '2019-02-12',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recB3KqUatn4qNl8X',
      date: '2019-02-13',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recO8ebfoI0lx5F2c',
      date: '2019-02-14',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec36HGda38vO3aFO',
      date: '2019-02-15',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recdQiNEHdSXzZM7Q',
      date: '2019-02-18',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recazSEdHQlPc9jQZ',
      date: '2019-02-19',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recHRAnRgLc0eU3nz',
      date: '2019-02-20',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recyq7zysA8REeYTX',
      date: '2019-02-21',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recr8BJfGmBl1QGxF',
      date: '2019-02-22',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'rece3fw3dHofv7Myu',
      date: '2019-02-25',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Teacher Workday',
    },
    {
      id: 'reclrpCAFbfm9BGrt',
      date: '2019-02-26',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recLRpkqHar121J9Z',
      date: '2019-02-27',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec7Xq7GKjVeai5xl',
      date: '2019-02-28',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recWHcK1YmB9eELKl',
      date: '2019-03-01',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recDNwD0JQVzqvXzl',
      date: '2019-03-04',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recuB9ayCiYGjWVje',
      date: '2019-03-05',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recl2LotYdYxDb6PF',
      date: '2019-03-06',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec1mtxqRRA0LW8cN',
      date: '2019-03-07',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recS5VE9CrRswGkdB',
      date: '2019-03-08',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec6ETZnlfspLBB9h',
      date: '2019-03-11',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'reckamCx1KzMqr07T',
      date: '2019-03-12',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recVYEVaflildpEbP',
      date: '2019-03-13',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec264HtEeCuuFgQZ',
      date: '2019-03-14',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recMyhtxuGu63Broi',
      date: '2019-03-15',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recyO5CZcI2tXR2pA',
      date: '2019-03-18',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec15wC8G5RntcZcD',
      date: '2019-03-19',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recchSJ3w2uzkqKaR',
      date: '2019-03-20',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recT0NKaMxahc3UKW',
      date: '2019-03-21',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recQpIOzbqiWZY1Ei',
      date: '2019-03-22',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recxzRRt4zWWGz76C',
      date: '2019-03-25',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recv1gK44o3Xd0O8V',
      date: '2019-03-26',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recZv4YQX86738CcN',
      date: '2019-03-27',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recFEK8eY5a5fWxxQ',
      date: '2019-03-28',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec1MqoJaPjFgOtJr',
      date: '2019-03-29',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'rec2yvLwM2EKLea4G',
      date: '2019-04-01',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Spring Break',
    },
    {
      id: 'recrBtdcQImH7TABB',
      date: '2019-04-02',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Spring Break',
    },
    {
      id: 'recvXUcUq3UyIqMw6',
      date: '2019-04-03',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Spring Break',
    },
    {
      id: 'recGkrgd9LuuCeMlX',
      date: '2019-04-04',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Spring Break',
    },
    {
      id: 'recDZ7R10wFm9w1X3',
      date: '2019-04-05',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Spring Break',
    },
    {
      id: 'rec4mZIninxERYxVG',
      date: '2019-04-08',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recGPqjj47JEdlL1b',
      date: '2019-04-09',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec4OlpATVuIkk6Zn',
      date: '2019-04-10',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recZJr32V9386N0O6',
      date: '2019-04-11',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recLvS3m7HE0LEKVk',
      date: '2019-04-12',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec5wwQ3tkfwi1tmv',
      date: '2019-04-15',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recRYI8IPuI2egPVI',
      date: '2019-04-16',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recRlrCr3e3doWpN5',
      date: '2019-04-17',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recshL1hMOw97tToz',
      date: '2019-04-18',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'recMeQF4GRGPqSyUB',
      date: '2019-04-19',
      type: 'holiday',
      lessonCount: 1,
    },
    {
      id: 'rec5NLJoS4qu6Z9jM',
      date: '2019-04-22',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recD3iDCTERlu58tF',
      date: '2019-04-23',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recQQgto4GwH4S3XN',
      date: '2019-04-24',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recm8kM6Zt3SCXdOO',
      date: '2019-04-25',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recXrWnEB7dzMR0n4',
      date: '2019-04-26',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recA8QnEvsN5pRLOi',
      date: '2019-04-29',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recUZzw5HHbHMEgRV',
      date: '2019-04-30',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recDSGAfmSQDI3ETh',
      date: '2019-05-01',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recQrHYmNbzUdFDmc',
      date: '2019-05-02',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recLioVOmF1bwoxNK',
      date: '2019-05-03',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recihefDADHRodWtw',
      date: '2019-05-06',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recJHJ8szPeFViYv9',
      date: '2019-05-07',
      lessonCount: 1,
      type: 'class',
    },
    {
      id: 'recal3YYgxw2omOfE',
      date: '2019-05-08',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recGIisrzhBPE6jRb',
      date: '2019-05-09',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recyTC75uXmUObUb2',
      date: '2019-05-10',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec6VgPoLKE4FHedZ',
      date: '2019-05-13',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recukkSRBwPRz1pfP',
      date: '2019-05-14',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recxL8agbDRGXYpi9',
      date: '2019-05-15',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recS9ppVWcqU50CDj',
      date: '2019-05-16',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recT05BpHl0eYgXS3',
      date: '2019-05-17',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'rec3AKVPvAis0bDuz',
      date: '2019-05-20',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recTDTkXfDOUoUCEh',
      date: '2019-05-21',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recYDxcqePBZcqi2n',
      date: '2019-05-22',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recAmyptOEEcoDHmF',
      date: '2019-05-23',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recM5F0OYrIMTPVDD',
      date: '2019-05-24',
      type: 'flex',
      lessonCount: 1,
    },
    {
      id: 'recXpjsL5SNqcE4NC',
      date: '2019-05-27',
      type: 'holiday',
      lessonCount: 1,
      notes: 'Memorial Day ',
    },
    {
      id: 'recm5L1n3l7v17Bfk',
      date: '2019-05-28',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recCFcUQicusq3OfU',
      date: '2019-05-29',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recZVyT5Ds4rvGyLh',
      date: '2019-05-30',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recEu2EAjfojmeMNC',
      date: '2019-05-31',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recdpHMCZ1O0BExVt',
      date: '2019-06-03',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recbQYbqDtBOx1L7B',
      date: '2019-06-04',
      type: 'class',
      lessonCount: 1,
    },
    {
      id: 'recBRo7mBu6VoO4W3',
      date: '2019-06-05',
      lessonCount: 1,
      type: 'assessment',
    },
    {
      id: 'recWz0uQMi59FQLOb',
      date: '2019-06-06',
      type: 'assessment',
      lessonCount: 1,
    },
    {
      id: 'recgJQ314iZXrXZEG',
      date: '2019-06-07',
      lessonCount: 1,
      type: 'party',
    },
  ],
};
